# Generated by Django 4.0 on 2024-04-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('softwaremanage', '0001_initial'),
        ('nodemanage', '0001_initial'),
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnityTable',
            fields=[
                ('entity_index', models.AutoField(primary_key=True, serialize=False, verbose_name='entity index')),
                ('entity_pid', models.CharField(max_length=32, verbose_name='entity pid')),
                ('entity_parcialkey', models.TextField(null=True, verbose_name='entity parcial key')),
                ('entity_porecessid', models.CharField(max_length=20, null=True, verbose_name='entity process id')),
                ('entity_port', models.IntegerField(null=True, verbose_name='entity port')),
                ('entity_ip', models.CharField(max_length=15, verbose_name='entity ip')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_alive', models.BooleanField(default=False, verbose_name='entity alive')),
                ('node_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodemanage.nodetable', verbose_name='node id')),
                ('software_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softwaremanage.softwaretable', verbose_name='software id')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.usertable', verbose_name='user id')),
            ],
        ),
    ]
