# Generated by Django 4.0 on 2024-04-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitymanage', '0002_kgcparamtertable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kgcparamtertable',
            name='id',
        ),
        migrations.AlterField(
            model_name='kgcparamtertable',
            name='kgc_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='kgc id'),
        ),
    ]
