# Generated by Django 4.0 on 2024-05-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitymanage', '0004_remove_enitytable_entity_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enitytable',
            name='software_name',
            field=models.CharField(default=0, max_length=20, verbose_name='software name'),
            preserve_default=False,
        ),
    ]
