# Generated by Django 4.0 on 2024-05-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitymanage', '0002_publicparamterstable_entityinfo_software_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityinfo',
            name='entity_port',
        ),
        migrations.AddField(
            model_name='entityinfo',
            name='entity_listening_port',
            field=models.IntegerField(null=True, verbose_name='entity listening port'),
        ),
        migrations.AddField(
            model_name='entityinfo',
            name='entity_sending_port',
            field=models.IntegerField(null=True, verbose_name='entity sending port'),
        ),
    ]
