# Generated by Django 4.0 on 2024-11-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entitymanage', '0003_remove_entityinfo_entity_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicparamterstable',
            name='domain_id',
            field=models.CharField(default='98657b1d3ea5b3d5266d6961d98c1152', max_length=32, verbose_name='domain_id'),
            preserve_default=False,
        ),
    ]
