# Generated by Django 4.0 on 2024-04-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NodeTable',
            fields=[
                ('node_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='node id')),
                ('node_ip', models.CharField(max_length=15, verbose_name='node ip')),
                ('node_desc', models.TextField(null=True, verbose_name='node descryption')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='LogTable',
            fields=[
                ('log_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='log id')),
                ('log_type', models.CharField(max_length=20, verbose_name='log type')),
                ('log_desc', models.TextField(null=True, verbose_name='log descryption')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('log_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nodemanage.nodetable', verbose_name='log node')),
            ],
        ),
    ]
