# Generated by Django 4.0 on 2024-04-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodemanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetable',
            name='node_port',
            field=models.IntegerField(default=0, verbose_name='node port'),
            preserve_default=False,
        ),
    ]
