# Generated by Django 4.0 on 2024-05-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodemanage', '0002_nodetable_node_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodetable',
            name='node_is_alive',
            field=models.BooleanField(default=False, verbose_name='node alive'),
        ),
        migrations.AlterField(
            model_name='nodetable',
            name='node_ip',
            field=models.GenericIPAddressField(verbose_name='node ip'),
        ),
    ]
