# Generated by Django 4.0 on 2024-11-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainTable',
            fields=[
                ('domain_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='domain id')),
                ('domain_ip', models.GenericIPAddressField(verbose_name='domain ip')),
                ('domain_port', models.IntegerField(verbose_name='domain port')),
            ],
        ),
    ]
