# Generated by Django 4.0 on 2024-04-08 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareTable',
            fields=[
                ('software_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='software_id')),
                ('software_version', models.CharField(max_length=50, verbose_name='software version')),
                ('software_name', models.CharField(max_length=20, verbose_name='software name')),
                ('software_hash', models.CharField(max_length=16, verbose_name='software hash')),
                ('software_desc', models.TextField(null=True, verbose_name='software descryption')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.usertable', verbose_name='user id')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareLocation',
            fields=[
                ('softwarelocation_index', models.AutoField(primary_key=True, serialize=False, verbose_name='software index')),
                ('node_ip', models.CharField(max_length=15, verbose_name='node ip')),
                ('pc_ip', models.CharField(max_length=15, verbose_name='pc ip')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('software_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='softwaremanage.softwaretable', verbose_name='software id')),
            ],
        ),
        migrations.CreateModel(
            name='RegistSoftwareTable',
            fields=[
                ('rsoftware_index', models.AutoField(primary_key=True, serialize=False, verbose_name='rsoftware index')),
                ('rsoftware_name', models.CharField(max_length=20, verbose_name='rsoftware name')),
                ('rsoftware_path', models.CharField(max_length=50, verbose_name='rsoftware path')),
                ('rsoftware_version', models.CharField(max_length=50, verbose_name='rsoftware version')),
                ('node_ip', models.CharField(max_length=15, verbose_name='node ip')),
                ('pc_ip', models.CharField(max_length=15, verbose_name='pc ip')),
                ('rsoftware_desc', models.TextField(null=True, verbose_name='rsoftware descryption')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanage.usertable', verbose_name='user id')),
            ],
        ),
    ]
