# Generated by Django 4.0 on 2024-11-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DDSInfoTable',
            fields=[
                ('entity_pid', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='entity pid')),
                ('dds_type', models.IntegerField(verbose_name='dds type')),
                ('source_ip', models.GenericIPAddressField(verbose_name='source ip')),
                ('source_port', models.IntegerField(verbose_name='source port')),
                ('destination_ip', models.GenericIPAddressField(verbose_name='destination ip')),
                ('destination_port', models.IntegerField(verbose_name='destination port')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
    ]
