# Generated by Django 4.0 on 2024-11-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsmanage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacketID',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('last_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ddsinfotable',
            name='destination_mac',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17, verbose_name='destination mac'),
        ),
        migrations.AddField(
            model_name='ddsinfotable',
            name='destination_mask',
            field=models.CharField(default='255.255.255.255', max_length=15, verbose_name='destination mask'),
        ),
        migrations.AddField(
            model_name='ddsinfotable',
            name='source_mac',
            field=models.CharField(default='00:00:00:00:00:00', max_length=17, verbose_name='source mac'),
        ),
        migrations.AddField(
            model_name='ddsinfotable',
            name='source_mask',
            field=models.CharField(default='255.255.255.255', max_length=15, verbose_name='source mask'),
        ),
    ]
