# Generated by Django 4.0 on 2024-11-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddsmanage', '0002_packetid_ddsinfotable_destination_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ddsinfotable',
            name='protocol_type',
            field=models.IntegerField(default=1, verbose_name='protocol type'),
            preserve_default=False,
        ),
    ]
