# Generated by Django 4.0 on 2024-04-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerTable',
            fields=[
                ('manager_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='manager id')),
                ('manager_name', models.CharField(max_length=20, verbose_name='manager name')),
                ('manager_pwd', models.CharField(max_length=20, verbose_name='manager password')),
                ('manager_phone', models.CharField(max_length=11, null=True, verbose_name='manager phone')),
                ('manager_email', models.EmailField(max_length=254, null=True, verbose_name='manager email')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterTable',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='user id')),
                ('user_name', models.CharField(max_length=20, verbose_name='user name')),
                ('user_pwd', models.CharField(max_length=20, verbose_name='user password')),
                ('user_phone', models.CharField(max_length=11, null=True, verbose_name='user phone')),
                ('user_email', models.EmailField(max_length=254, null=True, verbose_name='user email')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='user id')),
                ('user_name', models.CharField(max_length=20, verbose_name='user name')),
                ('user_row', models.CharField(max_length=20, verbose_name='user row')),
                ('user_pwd', models.CharField(max_length=16, verbose_name='user password')),
                ('user_phone', models.CharField(max_length=11, null=True, verbose_name='user phone')),
                ('user_email', models.EmailField(max_length=254, null=True, verbose_name='user email')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
            ],
        ),
    ]
